assets:
  android.keystore: zerocracy/home#assets/aintshy/android.keystore
  settings.xml: zerocracy/home#assets/aintshy/settings.xml
  pubring.gpg: zerocracy/home#assets/pubring.gpg
  secring.gpg: zerocracy/home#assets/secring.gpg
  s3cfg: zerocracy/home#assets/s3cfg
docker:
  image: yegor256/aintshy-android
deploy:
  script: |
    mvn clean install -Paintshy --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=aintshy-android.xml
    s3cmd --no-progress put aintshy-android.xml --config=../s3cfg s3://pdd.teamed.io/aintshy-android.xml
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean install -Psign -Pqulice -Paintshy --errors --settings ../settings.xml
  commanders:
  - yegor256
merge:
  script: |-
    mvn help:system clean install -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders: []
architect:
- yegor256
- karato